# Generated by Django 4.2.1 on 2023-06-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_file_image_alter_file_pdf_alter_images_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audio',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
