# Generated by Django 4.2.1 on 2023-06-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_audio_delete_images_delete_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='audio',
            field=models.FileField(blank=True, upload_to='media/files/audios/'),
        ),
        migrations.AddField(
            model_name='file',
            name='video',
            field=models.FileField(blank=True, upload_to='media/files/videos/'),
        ),
    ]
