# Generated by Django 4.2.1 on 2023-06-04 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_file_audio_file_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='descriptiion',
            new_name='description',
        ),
    ]
