# Generated by Django 4.2.1 on 2023-06-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_descriptiion_file_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
        migrations.RemoveField(
            model_name='file',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='file',
            name='image',
        ),
        migrations.RemoveField(
            model_name='file',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='file',
            name='video',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, upload_to='media/files/'),
        ),
        migrations.AddField(
            model_name='file',
            name='num_downloads',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='num_shares',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
