# Generated by Django 4.2.1 on 2023-06-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_feed_remove_file_audio_remove_file_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='audio',
        ),
        migrations.AddField(
            model_name='file',
            name='image',
            field=models.FileField(blank=True, upload_to='media/files/'),
        ),
        migrations.AddField(
            model_name='file',
            name='pdf',
            field=models.FileField(blank=True, upload_to='media/files/'),
        ),
        migrations.AddField(
            model_name='file',
            name='video',
            field=models.FileField(blank=True, upload_to='media/files/'),
        ),
    ]
